name: 'Bambu Lab Driver Funcional'
packageKey: 'pattetech.bambulab.final.v2' # Chave final para um começo limpo
version: '1.0.0'
author: 'Patrick Teixeira'
description: 'Driver para Bambu Lab com configuração manual'
permissions:
  lan: {}
profiles:
  - name: bambulab-printer-manual