# Este é o nosso config.yml, mas dentro da estrutura do Hello World
name: 'Bambu Lab Printer'
packageKey: 'bambu-printer-patricktd-v2' # Mudei um pouco para garantir que é uma nova versão
version: '2025-07-18T16:00:00.000Z'
author: 'Patrick TD'
description: 'Driver para descobrir e controlar impressoras Bambu Lab localmente.'
license: 'Apache-2.0'

device-profiles:
  - name: bambulab.discovered-printer.v1
  - name: bambulab.discovery.v1

discovery:
  - type: ssdp
    ssdp_term: "urn:bambulab-com:device:3dprinter:1"
    device_profile: bambulab.discovered-printer.v1

fingerprints:
  - id: "bambu-lab/discovery-device-v2" # Mudei um pouco para não haver cache
    deviceLabel: "Bambu Lab Discovery"
    profile: bambulab.discovery.v1
    driver: 'bambu-printer-patricktd-v2'