describe("JSON validation", function()
  it("decodes capabilities/patchprepare64330.status.json", function()
    local json = require "dkjson"
    local file = assert(io.open("capabilities/patchprepare64330.status.json", "r"))
    local content = file:read("*a")
    file:close()
    local obj, pos, err = json.decode(content, 1, nil)
    assert.is_not_nil(obj, err or ("invalid json at pos " .. tostring(pos)))
  end)
end)
