name: 'BambuLab MQTT Printer'
packageKey: 'pattetech.bambulab.driver' # <<<<< VOCÊ PRECISA ADICIONAR ESTA LINHA E MUDAR PARA ALGO ÚNICO
version: '0.1.0' # Versão incrementada
description: 'Driver Edge para impressoras Bambu Lab via MQTT com suporte a CA Cert'
author: 'Patrick Teixeira'
permissions:
  lan: # Permissão para acesso à rede local
    description: "Necessário para conectar à impressora via MQTT"
  discovery: # Permissão para descoberta de dispositivos (opcional)
    description: "Permite descobrir a impressora na rede"
