name: 'Bambu Lab Printer Driver'
packageKey: 'pattetech.bambulab.driver' 
version: '0.0.1' # Versão incrementada
description: 'Driver Edge para impressoras Bambu Lab via MQTT com suporte a CA Cert'
author: 'Patrick Teixeira'
permissions:
  lan: # Permissão para acesso à rede local
    description: "Necessário para conectar à impressora via MQTT"
  discovery: # Permissão para descoberta de dispositivos (opcional)
    description: "Permite descobrir a impressora na rede"
